[project]
name = "burrobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.6.0",
    "numpy>=1.26.4",
    "pygame>=2.6.1",
    "pyserial>=3.5",
    "ruff>=0.6.9",
    "tensorflow>=2.17.0",
]
